---
- name: 'restart docker'
  systemd:
    state: restarted
    daemon_reload: true
    name: docker
  listen: "restart docker"


- name: 'restart smbd'
  systemd:
    state: restarted
    daemon_reload: true
    name: smbd
  listen: "restart smbd"    